using System.Text.Json.Serialization;
using PKHeX.Models;

namespace PKHeX.Helpers;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.Never)]
[JsonSerializable(typeof(SaveFileHandle))]
[JsonSerializable(typeof(SaveFileInfo))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(SuccessMessage))]
[JsonSerializable(typeof(ExportSaveResponse))]
[JsonSerializable(typeof(ShowdownResponse))]
[JsonSerializable(typeof(RibbonCountResponse))]
[JsonSerializable(typeof(RivalNameResponse))]
[JsonSerializable(typeof(BattlePointsResponse))]
[JsonSerializable(typeof(CoinsResponse))]
[JsonSerializable(typeof(RecordsResponse))]
[JsonSerializable(typeof(EventFlagResponse))]
[JsonSerializable(typeof(EventConstResponse))]
[JsonSerializable(typeof(SecondsPlayedResponse))]
[JsonSerializable(typeof(SecondsToStartResponse))]
[JsonSerializable(typeof(SecondsToFameResponse))]
[JsonSerializable(typeof(HallOfFameResponse))]
[JsonSerializable(typeof(MysteryGiftsResponse))]
[JsonSerializable(typeof(MysteryGiftCardResponse))]
[JsonSerializable(typeof(MysteryGiftFlagsResponse))]
[JsonSerializable(typeof(SecretBaseResponse))]
[JsonSerializable(typeof(EntralinkResponse))]
[JsonSerializable(typeof(PokePelagoResponse))]
[JsonSerializable(typeof(FestivalPlazaResponse))]
[JsonSerializable(typeof(PokeJobsResponse))]
[JsonSerializable(typeof(PokemonStats))]
[JsonSerializable(typeof(HiddenPowerInfo))]
[JsonSerializable(typeof(CharacteristicInfo))]
[JsonSerializable(typeof(EvolutionEntry))]
[JsonSerializable(typeof(EvolutionInfo))]
[JsonSerializable(typeof(SpeciesFormInfo))]
[JsonSerializable(typeof(SpeciesFormsInfo))]
[JsonSerializable(typeof(ConversionResult))]
[JsonSerializable(typeof(LocationInfo))]
[JsonSerializable(typeof(MetLocationsInfo))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(PokemonSummary))]
[JsonSerializable(typeof(PokemonDetail))]
[JsonSerializable(typeof(TrainerInfo))]
[JsonSerializable(typeof(TrainerInfoResponse))]
[JsonSerializable(typeof(LegalityResult))]
[JsonSerializable(typeof(RibbonData))]
[JsonSerializable(typeof(ContestStats))]
[JsonSerializable(typeof(TrainerCard))]
[JsonSerializable(typeof(TrainerAppearance))]
[JsonSerializable(typeof(BadgeData))]
[JsonSerializable(typeof(PIDInfo))]
[JsonSerializable(typeof(PKMDataResponse))]
[JsonSerializable(typeof(BoxInfo))]
[JsonSerializable(typeof(DaycareData))]
[JsonSerializable(typeof(ItemSlot))]
[JsonSerializable(typeof(PouchData))]
[JsonSerializable(typeof(PokedexEntry))]
[JsonSerializable(typeof(HallOfFameEntry))]
[JsonSerializable(typeof(MailMessage))]
[JsonSerializable(typeof(MysteryGiftCard))]
[JsonSerializable(typeof(NamedEntity))]
[JsonSerializable(typeof(NameResponse))]
[JsonSerializable(typeof(SpeciesListResponse))]
[JsonSerializable(typeof(MovesListResponse))]
[JsonSerializable(typeof(AbilitiesListResponse))]
[JsonSerializable(typeof(ItemsListResponse))]
[JsonSerializable(typeof(NaturesListResponse))]
[JsonSerializable(typeof(TypesListResponse))]
[JsonSerializable(typeof(List<PokemonSummary>))]
[JsonSerializable(typeof(List<RibbonData>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<BoxInfo>))]
[JsonSerializable(typeof(List<PouchData>))]
[JsonSerializable(typeof(List<PokedexEntry>))]
[JsonSerializable(typeof(List<HallOfFameEntry>))]
[JsonSerializable(typeof(List<MailMessage>))]
[JsonSerializable(typeof(List<MysteryGiftCard>))]
[JsonSerializable(typeof(List<NamedEntity>))]
[JsonSerializable(typeof(List<bool>))]
[JsonSerializable(typeof(List<int>))]
[JsonSerializable(typeof(List<EvolutionEntry>))]
[JsonSerializable(typeof(List<SpeciesFormInfo>))]
[JsonSerializable(typeof(List<LocationInfo>))]
[JsonSerializable(typeof(List<RibbonEntry>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(RibbonEntry))]
[JsonSerializable(typeof(RibbonListResponse))]
[JsonSerializable(typeof(HandleCountResponse))]
// Friendship models
[JsonSerializable(typeof(FriendshipData))]
// Memory models
[JsonSerializable(typeof(MemoryInfo))]
[JsonSerializable(typeof(MemoriesData))]
[JsonSerializable(typeof(MemoryStringsData))]
// Form models
[JsonSerializable(typeof(FormData))]
[JsonSerializable(typeof(FormInfo))]
[JsonSerializable(typeof(AvailableFormsData))]
[JsonSerializable(typeof(List<FormInfo>))]
// Batch models
[JsonSerializable(typeof(BoxSlotLocation))]
[JsonSerializable(typeof(BoxSlotLocation[]))]
[JsonSerializable(typeof(BatchLegalityResult))]
[JsonSerializable(typeof(BatchLegalityResponse))]
[JsonSerializable(typeof(BatchModification))]
[JsonSerializable(typeof(BatchModification[]))]
[JsonSerializable(typeof(BatchOperationResult))]
[JsonSerializable(typeof(BatchOperationResponse))]
[JsonSerializable(typeof(BatchClearResponse))]
[JsonSerializable(typeof(BoxStatsData))]
[JsonSerializable(typeof(List<BatchLegalityResult>))]
[JsonSerializable(typeof(List<BatchOperationResult>))]
// Tera Type models
[JsonSerializable(typeof(TeraTypeData))]
[JsonSerializable(typeof(TeraTypeInfo))]
[JsonSerializable(typeof(TeraTypesListResponse))]
[JsonSerializable(typeof(List<TeraTypeInfo>))]
public partial class JsonContext : JsonSerializerContext
{
}
