<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- Size optimization -->
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <EventSourceSupport>false</EventSourceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>

    <!-- Trimming -->
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\PKHeX\PKHeX.Core\PKHeX.Core.csproj" />
    <PackageReference Include="BytecodeAlliance.Componentize.DotNet.Wasm.SDK"
                      Version="0.7.0-preview00010" />
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM"
                      Version="10.0.0-rc.1.26117.1" />
    <PackageReference Include="runtime.linux-x64.Microsoft.DotNet.ILCompiler.LLVM"
                      Version="10.0.0-rc.1.26117.1" />
    <PackageReference Include="runtime.wasi-wasm.Microsoft.DotNet.ILCompiler.LLVM"
                      Version="10.0.0-rc.1.26117.1" />
  </ItemGroup>


</Project>
